Добавляет класс Task
htmlacademy-yii/38064-task-force-1 pull request #2
Opened 2019-10-13 18:59 UTC by nikopol-fw

2019-10-17 10:55 UTC, kostromich requested changes
1. Пожалуйста проверь свой код на соответствие PSR-1/12.
2. Нам нужно подготовить список доступных действий, ролей и статусов таким образом, чтобы было понятно, что каждый из них обозначает, связать числовые id, которые ты уже задал с текстовым описанием.
Лучше всего это сделать используя твои же id:
```php
private $availableStatuses = [
    self::STATUS_NEW => 'Новая'
];
```
Этот текст в будущем переиспользуем, напирмер, как текст для кнопок.
3. Аналогично п. 2 для Ролей
4. Аналогично п. 2 для Действий
5. Ты упоминал о возможном разделении сущностей - не ограничивай себя. Если считаешь, что Роли/Действия/Статусы будут лучше смотреться в отдельных классах - лучше вынеси сразу
6. Методы для управления задачей предлагаю пока не описывать. Необязательно => Если очень хочется и умеешь, то можно написать интерфейс или наследоваться от абстрактного класса.
7. Не реализован метод получения будущего статуса в зависимости от переданного действия. Примерная сигнатура метода:
```php
public function getNextStatus($action)
{
    // some magic
    return $nextStatus;
}
```
8. Вкусовщина: немного смущает терминология: refuse, start, finish, completition в свойствах, методах и статусах. В частности $completitionDate - это дата, когда задача должна быть выполнена или дата фактического выполнения? Если второй пункт, то где тогда дедлайн? Нужен ли он?
9. Типизация. $completitionDate - unixtimestamp (integer) или строка YYYY-MM-DD HH:ii:ss?

2019-10-18 20:48 UTC, kostromich requested changes
Почти.
Оставил несколько вопросов, пиши сразу в telegram или скайп

2019-10-18 20:48 UTC, kostromich commented on src/Task.php
> +        $this->status = $status;
Конструктор предполагает создание новой задачи: статус мы не передаём.
Параметры должны быть выстроены по важности: наверное, автора стоит указывать в самом начале?
Почему именной такой порядок?

2019-10-18 20:48 UTC, kostromich commented on src/Task.php
> +        $this->contractorId = $contractorId;
Исполнитель назначается задаче не в момент её создания, а позже, когда исполнитель откликается на задачу.

2019-10-18 20:48 UTC, kostromich commented on src/Task.php
> +        $this->deadline = $deadline;
Дедлайн у нас обязательное свойство? Может быть задача без срока?

2019-10-18 20:48 UTC, kostromich commented on src/Task.php
> +    //    public function getCurrentStatus()
Закомментированный код можем удалить. git всё помнит

2019-10-19 11:48 UTC, nikopol-fw commented on src/Task.php
> +    //    public function getCurrentStatus()
Это так строго?
Это ведь не защита

2019-10-19 11:49 UTC, nikopol-fw commented on src/Task.php
> +        $this->deadline = $deadline;
Да, увидел, что может быть. Уберу.

2019-10-19 11:51 UTC, nikopol-fw commented on src/Task.php
> +        $this->contractorId = $contractorId;
Именно поэтому значение у этого параметра по-умолчанию null.
А если мы заходим на страницу задачи у которой уже есть исполнитель. Тогда при создании класса будет проще его сразу передать и записать в поле.

2019-10-19 11:56 UTC, nikopol-fw commented on src/Task.php
> +        $this->status = $status;
А что класс будет использоваться только для создания новых задач, а для уже существующих нет?
Зачем тогда внутри него логика для изменения статуса?
Единственное что я бы сделал это возможно завел значение по-умолчанию для статуса.

Насчет порядка, а почему нет? Где определяется эта важность?
Такой порядок просто потому что мне так удобно. Ведь это вкусовщина и технически ни на что не влияет.

2019-10-21 12:14 UTC, kostromich reviewed
Изменения можно внести в следующем задании.

2019-10-21 12:14 UTC, kostromich commented on src/Task.php
> +    //    public function getCurrentStatus()
Именно так строго: это общая культура написания кода.

2019-10-21 12:14 UTC, kostromich commented on src/Task.php
> +        $this->deadline = $deadline;
Тогда имеет смысл сделать пустое значение по умолчанию.

2019-10-21 12:14 UTC, kostromich commented on src/Task.php
> +    /** @var int */
Для nullable-свойств подсказка типа будет выглядеть так: `/** @var int | null */`

2019-10-21 12:14 UTC, kostromich commented on src/Task.php
> +        $this->status = $status;
Пока непонятно, как будет использоваться этот класс: только для новых или для существующих. Механизм подгрузки существующих данных может быть любым.

Приоритеты определяются обязательностью свойств: опциональные - в конце.
Остальное на усмотрение разработчика.

2019-10-21 12:17 UTC, merged